### ISSUE TITLE
Add more code to cover rocketmq behavior

### ISSUE THREAD

**Issue by drpmma** [apache/rocketmq-apis#18]
**Is your feature request related to a problem? Please describe.**
Current code cannot cover all rocketmq behavior such as `FLUSH_DISK_TIMEOUT` and `FLUSH_SLAVE_TIMEOUT`. And the similar codes  should be grouped according to usage.

**Describe the solution you'd like**
Add more code and group them by usage.

**Describe alternatives you've considered**

**Additional context**
rocketmq ResponseCode
https://github.com/apache/rocketmq/blob/8745d4c538d5c96e65a56f6278029c5765e7d922/common/src/main/java/org/apache/rocketmq/common/protocol/ResponseCode.java#L22

**Comment by lizhanhui** [comment]
Close as the pull request has been merged.
