### ISSUE TITLE
Make service interface orthogonal and independent

### ISSUE THREAD

**Issue by drpmma** [apache/rocketmq-apis#26]
The service interface should be orthogonal and independent of other services. 

So I am proposing to add `Endpoints` filed to `QueryRouteRequest` and `QueryAssignmentRequest`, and add `auto_renew` to `ReceiveMessageRequest`. In this way, the service interface will not depend on `access_point` and  `client_type` in `Settings`.

**Comment by aaron-ai** [comment]
Nice suggestion.

**Comment by lizhanhui** [comment]
+1

**Comment by lizhanhui** [comment]
Close as the pull request has been merged.
